Check for existing release tag

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -21,8 +21,8 @@ jobs:
         run: |
           . usr/local/share/bastille/version.sh
           if ! [[ "$BASTILLE_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]{8}$ ]]; then
-              echo "Invalid version format"
-              exit 1
+            echo "Invalid version format"
+            exit 1
           fi
           echo "RELEASE_VERSION=v$BASTILLE_VERSION" >> $GITHUB_ENV
 
@@ -30,6 +30,9 @@ jobs:
         run: |
           git config user.name "GitHub Actions"
           git config user.email "github-actions@users.noreply.github.com"
+          if git rev-parse "$RELEASE_VERSION" >/dev/null 2>&1; then
+            echo "Tag already exists"
+          fi
           git tag ${RELEASE_VERSION}
           git push origin ${RELEASE_VERSION}
 
